#add this file to your meteor package as `.travis.yml`
language: node_js  
node_js:
  - "0.10"
before_install:
  - "curl -L http://git.io/3l-rRA | /bin/sh"
env:
# how we can laika options
  - LAIKA_OPTIONS="-t 5000"